config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  devise_for :users
  post '/tasks/:id/done', to: 'tasks#done', as: 'done_task'
  post '/tasks/:id/to_do', to: 'tasks#to_do', as: 'to_do_task'
  post '/tasks/:id/play_pause', to: 'tasks#play_pause', as: 'play_pause'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    scope :to_do,   ->(user){ where(user_id: user.id, done:false) }
    scope :done,   ->(user){ where(user_id: user.id, done:true) }
    scope :played, ->(user){ where(user_id: user.id, playing_status:true) } 

    def play_pause
        if self.playing_status
            self.duration += (Time.now.to_i - self.updated_at.to_i)
        end
        self.playing_status = !self.playing_status
        self.save        
    end

    def update_duration
        if self.playing_status
            self.duration += (Time.now.to_i - self.updated_at.to_i)
        end
        self.save
    end

    def self.update_all_playing(user)
        Task.played(user).all.select { |r| r.update_duration }
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :update_duration, only: [:index]

  def index
    @task = Task.new
    @to_do =  Task.to_do(current_user)
    @done = Task.done(current_user)
  end

  def create
    @task = Task.new(task_parameter)
    @task.user_id = current_user.id
    @task.save
  end

  def edit
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_parameter)
  end

  def done
    @task = Task.find(params[:id])
    @task.playing_status = false
    @task.update(done: true)
  end

  def to_do
    @task = Task.find(params[:id])
    @task.update(done: false)
  end

  def play_pause
    @task = Task.find(params[:id])
    @task.play_pause
  end

  def destroy
    @task = Task.find(params[:id])
    @id = @task.id
    @task.destroy
  end
  private
  
  def task_parameter
    params.require(:task).permit(:title,:description)
  end

  def update_duration
    Task.update_all_playing(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
    def time_in_distance(t)
        mm, ss = t.divmod(60)            
        hh, mm = mm.divmod(60)           
        dd, hh = hh.divmod(24) 
        render "duration", mm: mm, ss:ss, dd:dd, hh:hh
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoListApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% if signed_in? %>
          <%= link_to "Salir", destroy_user_session_path, method: :delete %>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_duration.html.erb
<span class = "days"> <%=dd %></span> days, <span class = "hours"><%=hh%> </span> hours, <span class = "minutes"> <%=mm%> </span> minutes and <span class = "seconds"><%=ss%></span> seconds 

app/views/tasks/_form.html.erb
<div id="task-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <%= form_for @task, remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.text_field :title, class: "form-control input-lg", placeholder: "Title" %>
          </div>
          <div class="form-group">
            <%= f.text_area :description, class: "form-control input-lg", placeholder: "Description" %>
          </div>
        </div>

        <div class="modal-footer">
          <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
    <div class="list-group-item list-group-item-action flex-column align-items-start <%= "playing-task" if task.playing_status%>" id="<%= task.id%>">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1 text-center"><%= task.title%></h5>
            <div class= "row">
            <small><%=time_ago_in_words(task.created_at)%></small>
            </div>
        </div>
        <div class="row">
            <div class="col-12 description">
                <p class="mb-1 "><%= simple_format(task.description) %></p>
            </div>
            <div class="col-12">
                <p class="mb-1"><%= time_in_distance(task.duration)%></p>
            </div>
        </div>
        <p>
            <%= link_to 'Edit', edit_task_path(task), remote:true, :class => "btn" %>|
            <% if task.done%>
            <%= link_to 'Re Open', to_do_task_path(task), :method => :post, remote:true, :class => "btn" %>|
            <% else %>
            <%= link_to 'Done', done_task_path(task), :method => :post, remote:true, :class => "btn" %>|
            <% end %>
            <%= link_to 'Destroy',  task,  method: :delete, remote:true, data: { confirm: 'Are you sure?' } %>
            <% unless task.done%>
                |<%= link_to task.playing_status ? 'Pause' : 'Play', play_pause_path(task), :method => :post, remote:true, :class => "btn" %>
            <% end%>        
        </p>
    </div>

app/views/tasks/create.js.erb
<% if @task.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('#todo-container').prepend(' <%= j render "task", task: @task %>');
  $('.alert-success').html("Task has been created successfully").show();
  $('#task-modal').remove();
  $('.modal-backdrop').remove();
<% else %>
  // show first error
  alert('<%= @task.errors.full_messages[0] %>');
<% end %>

app/views/tasks/destroy.js.erb
$('#<%= j "#{@id}" %>').remove()

app/views/tasks/done.js.erb
$('#<%= j "#{@task.id}" %>').remove()
$('#done-container').prepend('<%= j render "task", task: @task %>')

app/views/tasks/edit.js.erb
$('<%= j render "form", title: "Editar Task" %>').modal();

app/views/tasks/index.html.erb
<%= link_to 'Create', new_task_path(@task),remote: true, :class => "btn btn-primary" %>
<div class="row">
    <div class="col-md-6 col-sm-12" >
        <h2 class="text-center">Todo List</h2>
        <div id="todo-container">   
        <% if @to_do%>
            <% @to_do.each do |task|%>
                <%= render "task", task: task %>
            <% end %>
        <% end %>
        </div>
    </div>
    <div class="col-md-6 col-sm-12" >
        <h2 class="text-center">Done List</h2>
        <div id="done-container">
        <% if @done%>
            <% @done.each do |task|%>
                <%= render "task", task: task %>
            <% end %>
        <% end %>
        </div>
    </div>
  </div>
  <script>
    new TasksIndex()
  </script>

app/views/tasks/new.js.erb
$('<%= j render "form", title: "Crear Task" %>').modal();

app/views/tasks/play_pause.js.erb
$('#<%= j "#{@task.id}" %>').replaceWith('<%= j render "task", task: @task %>')

app/views/tasks/to_do.js.erb
$('#<%= j "#{@task.id}" %>').remove()
$('#todo-container').prepend('<%= j render "task", task: @task %>')

app/views/tasks/update.js.erb
$('#<%= j "#{@task.id}" %>').replaceWith('<%= j render "task", task: @task %>')
$('#task-modal').remove();
$('.modal-backdrop').remove();